repos:
- repo: git@github.com:buzzoole/pre-commit-php.git
  rev: 1.2.1
  hooks:
  - id: php-lint
  - id: php-cs
    files: \.(php)$
    args: [--standard=PSR2 -p --config-set ignore_warnings_on_exit 1]
  - id: php-cs-fixer
    files: \.(php)$
    args: ["--rules=@PSR2,binary_operator_spaces -vv --allow-risky=no"]
